- bower.json
- dist/spectral-workbench.css
- dist/spectral-workbench.js
- examples/index.html
- package.json
- src/SpectralWorkbench.Graph.js
> fixes for #6 zoom interface

- README.md
- bower.json
- dist/spectral-workbench.js
- examples/array.html
- package.json
- spec/javascripts/spectrum_spec.js
- src/SpectralWorkbench.Spectrum.js
> array-based constructor and test, closes #5

- README.md
- bower.json
- dist/spectral-workbench.js
- examples/array.html
- examples/index.html
- package.json
- spec/javascripts/spectrum_spec.js
- src/SpectralWorkbench.Datum.js
> operations and tagging without graphing

- package.json
> version bump in package.json

- README.md
- bower.json
- dist/spectral-workbench.js
- package.json
- spec/javascripts/spectrum_spec.js
- src/SpectralWorkbench.Graph.js
- src/SpectralWorkbench.Spectrum.js
> TSV support

- bower.json
- dist/spectral-workbench.js
- package.json
- src/SpectralWorkbench.Spectrum.js
> ignoring comments & blank lines in TSVs, built

- bower.json
- dist/spectral-workbench.js
- package.json
- spec/javascripts/spectrum_spec.js
- src/SpectralWorkbench.Spectrum.js
> Tsv comment handling

- Gruntfile.js
- README.md
- package.json
- spec/javascripts/set_spec.js
- spec/javascripts/ui_spec.js
> all but one test running headless in phantomjs

- .travis.yml
- Gruntfile.js
- README.md
- dist/spectral-workbench.js
- package.json
- spec/javascripts/graph_spec.js
- spec/javascripts/image_spec.js
- src/SpectralWorkbench.Graph.js
- src/SpectralWorkbench.Image.js
- src/SpectralWorkbench.Spectrum.js
- src/api/SpectralWorkbench.API.Operations.js
- src/ui/SpectralWorkbench.UI.ToolPaneTypes.js
> Travis update 2

- dist/spectral-workbench.js
- spec/javascripts/image_spec.js
- src/SpectralWorkbench.Graph.js
- src/SpectralWorkbench.Image.js
- src/SpectralWorkbench.Spectrum.js
- src/api/SpectralWorkbench.API.Operations.js
> better image-dom abstraction

- Gruntfile.js
- README.md
- dist/spectral-workbench.js
- examples/node-example.js
- package.json
- spec/javascripts/image_spec.js
- spec/javascripts/spectrum_spec.js
- src/SpectralWorkbench.Graph.js
- src/SpectralWorkbench.Image.js
- src/SpectralWorkbench.Spectrum.js
> passing more options explicitly via Image constructor

- README.md
- dist/spectral-workbench.js
- examples/node-example-import.js
- examples/node-example.js
- package.json
- spec/javascripts/image_spec.js
- src/SpectralWorkbench.Spectrum.js
> further image, CSV output, nodejs improvements

- dist/spectral-workbench.js
- package.json
- spec/javascripts/graph_spec.js
- spec/javascripts/image_spec.js
- spec/javascripts/spectrum_spec.js
- src/SpectralWorkbench.Datum.js
- src/SpectralWorkbench.Graph.js
- src/SpectralWorkbench.Image.js
- src/SpectralWorkbench.Spectrum.js
- src/api/SpectralWorkbench.API.Operations.js
- src/ui/SpectralWorkbench.UI.ToolPaneTypes.js
With v0.1.0 version bump to include v0.0.15 nodejs features.
> images now belong to spectra, spectra can be created from images

- bower.json
> removed bower version

- dist/spectral-workbench.js
- package.json
- spec/javascripts/graph_spec.js
- src/SpectralWorkbench.Image.js
updated version # in package.json
> accommodate imageless spectra, and tested

- package.json
- src/SpectralWorkbench.Image.js
- src/SpectralWorkbench.Spectrum.js
> fixes for sigfigs and image src assignment, closes #15

- dist/spectral-workbench.js
- package.json
followup to #38 with built files; tested
> followup build fix, ugh

- .travis.yml
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software
Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
Thanks!
> node version tweaks

- README.md
Fix #111
Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software
Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
Thanks!
> Add npm version badge to the README

- Code_of_Conduct.md
- Contributing.md
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software
Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
Thanks!
> Added CoC and Contributing guide

- Gruntfile.js
- dist/capture.dist.js
- examples/capture/index.html
As the title suggests, files #148 are now compiled in one file.
Resolves #151
@starkblaze01 @jywarren @ananyaarun could you take a look at this? Thanks.
> ADD: Compile capture.js subfiles into one file

- .travis.yml
- examples/index.html
- package.json
Works, although has an error. cc #155
> D3 v3.5.17

- examples/index.html
- package.json
> move all bower deps to npm

- README.md
@SidharthBansal @ananyaarun  @cesswairimu  Could you please review my PR ?
Fixes #145 
Thanks!
> updated README for issue #145

- cypress.json
- dist/capture.dist.js
- dist/spectral-workbench.js
- examples/capture/capture.js
- examples/capture/getUserMedia.js
Working from https://gosink.in/webrtc-switch-cameras-using-javascript-getusermedia/ to fix #178 
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode
> further attempts at facingMode environment

- .github/workflows/tests.yml
> Setup github actions CI instead of Travis

- package-lock.json
- package.json
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software
Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
Thanks!
> bump to v0.2.0
